- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - flask
    - psutil

- name: Copy doorbell webserver daemon config
  copy:
    src: webserver.service
    dest: /etc/systemd/system
    mode: 0644

- name: Start doorbell webserver on startup
  systemd:
    daemon_reload: yes
    enabled: yes
    name: webserver
    state: started