- include: install.yml

- name: Set system volume to maximum
  command: amixer set PCM -- 100%

- name: Store system volume setting accross boots
  command: sudo alsactl store

- name: Create doorbell home directory
  file:
    path: /opt/doorbell
    state: directory
    owner: pi

- name: Create logs directory
  file:
    path: /opt/doorbell/logs
    state: directory
    owner: pi

- name: Copy sound files
  copy:
    src: wav
    dest: /opt/doorbell
    owner: pi

- name: Disable audio dither to avoid white noise
  lineinfile:
    path: /boot/config.txt
    line: 'disable_audio_dither=1'
    state: present

- name: Copy doorbell daemon config
  copy:
    src: doorbell.service
    dest: /etc/systemd/system
    mode: 0644

- name: Start doorbell daemon on startup
  systemd:
    daemon_reload: yes
    enabled: yes
    name: doorbell
    state: started